# Generated by Django 3.2.16 on 2022-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Finanza', 'Finanza'), ('Mesa', 'Mesa'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Barman', 'Barman'), ('Garzon', 'Garzon')], max_length=7),
        ),
    ]
