# Generated by Django 3.2.16 on 2022-12-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=7, null=True)),
                ('turno', models.CharField(blank=True, max_length=9, null=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountUsuario',
            fields=[
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('celular', models.IntegerField()),
                ('is_client', models.BooleanField()),
                ('is_employee', models.BooleanField()),
                ('intentos', models.IntegerField()),
            ],
            options={
                'db_table': 'account_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountUsuarioGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'account_usuario_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountUsuarioUserPermi783D',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'account_usuario_user_permi783d',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AxesAccessattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=1025, null=True)),
                ('path_info', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_time', models.DateTimeField()),
                ('get_data', models.TextField(blank=True, null=True)),
                ('post_data', models.TextField(blank=True, null=True)),
                ('failures_since_start', models.IntegerField()),
            ],
            options={
                'db_table': 'axes_accessattempt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AxesAccessfailurelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=1025, null=True)),
                ('path_info', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_time', models.DateTimeField()),
                ('locked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'axes_accessfailurelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AxesAccesslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=1025, null=True)),
                ('path_info', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'axes_accesslog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_garzon', models.CharField(max_length=100)),
                ('fecha_hora', models.CharField(max_length=20)),
                ('detalle_boleta', models.CharField(max_length=1000)),
                ('total_neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('propina', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_det_ped', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_ped', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMesa',
            fields=[
                ('id_est_me', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finanza',
            fields=[
                ('id_finanza', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.BigIntegerField()),
                ('num_boleta', models.BigIntegerField()),
                ('fecha', models.CharField(max_length=25)),
                ('ingreso', models.BigIntegerField()),
                ('salida', models.BigIntegerField()),
                ('ganancia', models.BigIntegerField()),
            ],
            options={
                'db_table': 'finanza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.BigIntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('nombre_ins', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_m', models.CharField(max_length=50)),
                ('porcion', models.BigIntegerField()),
                ('tiempo', models.CharField(max_length=5)),
                ('detalle', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.BigIntegerField()),
                ('nombre_receta', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=500)),
                ('preparacion', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.BigIntegerField()),
                ('mensaje', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id_tipo_m', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.OneToOneField(db_column='id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.accountempleado')),
                ('capacidad', models.BigIntegerField()),
                ('id_empleado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoMenu',
            fields=[
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.pedido')),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pedido_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.accountusuario')),
                ('fecha_hora', models.CharField(max_length=20)),
                ('id_usuario', models.FloatField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id_solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.solicitud')),
                ('cantidad_soli', models.BigIntegerField()),
            ],
            options={
                'db_table': 'solicitud_insumo',
                'managed': False,
            },
        ),
    ]
